[package]
name = "thor_reforged"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2"
log = "0.4.17"
env_logger = "0.10.0"
rand = "0.8.5"
dyn-clone = "1.0.11"
num_cpus = "1.15.0"